producer.go
test/Gemfile
test/Gemfile.lock
test/end-to-end
test/kafka.test.json
test/test_helper.rb

This simulates a procedure similar to when a client application is
restarted (ie. its consumer groups are shutdown and start again anew).
Closes #15

Test consumer group reconnect scenario

---

Makefile
consumer.go
kafka.json.sample
server.go
test/end-to-end
test/kafka.test.json

Using Poll() means we have a more direct mapping to librdkafka functionality. Poll may also prioritize messages from Kafka, whereas with the channel-based approach we may end up with outdated events.

consumer: Switch to Poll()

---

Gopkg.lock
Gopkg.toml
Makefile
README.md
client.go
client_test.go
config.go
rafka.go
rafka_test.go
server.go
test/README.md
test/end-to-end

These test implementation details on a lower level than the end-to-end
tests and have access to APIs that rafka-rb doesn't yet (eg. consuming
multiple topics from the same client).
Closes #13

Add initial Go tests

---

producer.go

The librdkafka producer events channel should be consumed prior to
calling `Flush()`, otherwise we'll hit the flush timeout and outstanding
events will be reported by `Flush()` (for more info see
https://github.com/confluentinc/confluent-kafka-go/blob/v0.11.0/kafka/producer.go#L195-L215)
Therefore, we have to constantly consume events by the `Events()`
channel until the producer is `Close()`ed, therefore its events channel
is closed. We introduced a new goroutine, `consumeDeliveries` that does
just that, consumes events and logs any failures.
Some refactorings were also performed:
- `run()` is no longer a separate method/goroutine but is embedded in `Close()`
instead. This simplifies the Producer's internals.
- Use a sync.WaitGroup instead of close/done channels
Fixes #33

producer: Consume event channel in a goroutine

---

README.md
producer.go
rafka.go
rafka_test.go
server.go
stats.go
test/end-to-end

This allows users to monitor Rafka for errors that are not propagated to
the clients. Until now such errors were just being logged. It allows for
simple alerting rules (eg. alert when producer errors are more than 10).
We used the HGETALL Redis command, since the stats structure can be
considered a hash with stat names as keys and counters as values.
Part of #28

Implement stats redis command

---

README.md
rafka_test.go
server.go
test/Gemfile.lock
test/docker-compose.yml
test/end-to-end

Two or more messages with the same key will always be assigned to the
same kafka partition.
This feature will enable us to guarantee a consistent message
consumption order.

Add support for message keys in the producer

---

test/Gemfile.lock
test/end-to-end

This is a follow-up to https://github.com/skroutz/rafka-rb/pull/9.

Add test for manual offset management in rafka-rb

---

test/Gemfile.lock
test/end-to-end

This feature was added in rafka-rb 0.2.0 (https://github.com/skroutz/rafka-rb/pull/12).

Add end-to-end test for batch consuming

---

README.md
config.go
consumer.go
consumer_manager.go
kafka.json.sample
rafka.go
test/Dockerfile
test/kafka.test.json

* `Consumer.SetOffset()` uses the new `rdkafka.Consumer.StoreOffsets()`, which will store the offsets (related to the consumer config `enable.auto.offset.store: false`)
* the client no longer runs the periodic `c.commitOffsets()` loop. The goroutine and its relevant synchronization were completely removed. This is replaced with the `enable.auto.commit: true` consumer config.
* `Consumer.Run()` now after subscribing to the topics just waits for the `ctx.Done()`
* the `-i` flag is removed, replaced by the consumer config `auto.commit.interval.ms`
Closes #32

Use librdkafka auto commit and store offsets functionality

---

consumer.go

With this change, log lines like the following:
Unknown event type: kafka.OffsetsCommitted
now become:
OffsetsCommitted (<nil>, [r-0bc221[0]@unset r-0bc221[1]@1 r-0bc221[2]@unset r-0bc221[3]@unset])
This particular line means that there were no error committing offsets
(<nil>) on that in the foo topic, we committed the
offset 7 for partition 0 and no offset for partition 1.
This is a follow-up to ffe8e40.

Print information of committed offsets

---

consumer.go

Treat `Poll GroupCoordinator response error: Local: Broker transport failure` errors as transient.
For more info check out: https://github.com/edenhill/librdkafka/issues/1987#issuecomment-422008750

consumer: poll: ignore transient error

---

test/librdkafka.test.json

Completely remove librdkafka log output in test invocations, to reduce log clutter when running tests locally and in travis

dont log librdkafka messages in tests

---

README.md
main_test.go
server.go

This commit adds a new cmd in the likes of the redis [KEYS](https://redis.io/commands/keys) command.
It is used to list all the topics of the cluster in their fully qualified names.
Note: Normal redis `KEYS` command takes one argument which matches
it as a glob against all keyspace. We do indeed accept an argument for
the sake of compatibility but we ignore it.
Usage example:
```
localhost:6380> keys topics:
1) "topics:greetings"
2) "topics:__consumer_offsets"
3) "topics:another-topic"
```

server: Add support for KEYS cmd to list topics

---

.gitignore
README.md
client.go
consumer_manager.go
errors.go
main.go
server.go
test/end-to-end

This patch aims to minimize the downtime for producers and make the
shutdown process generally more robust. The flow is now the following:
1) shutdown signal is received
2) manager: stop accepting new consumers and close existing consumers
3) server: stop accepting new producers and close existing producers
5) shutdown and restart
This way, producer downtime is reduced to the time elapsed between (3)
and (5), which should be less than a second. Nevertheless, clients
should still have sane retry defaults configured anyway, because some
downtime will still occur.
Also added a hard timeout of 5 seconds around the shutdown process.

Shutdown revamp

---

consumer.go
server.go

In librdkafka/confluent-kafka-go we shouldn't call Poll() concurrently with
Close() or Unsubscribe(), since that might lead to race conditions. We
noticed such an issue when upgrading to librdkafka 0.11.6 and 1.0.0,
where consumers would block in Poll() forever if rafka attempted to shutdown
right in the middle of a call to Poll() (i.e. clients calling BLPOP). See
edenhill/librdkafka#2333 for background.
This patch synchronizes access between a consumer's Poll() and its
shutdown sequence, so that the two may never run concurrently.
Furthermore, if a consumer is terminated then calling Poll() will
immediately return nil without communicating with Kafka at all.
Fixes consumers blocking on Poll() when the server is shutting down,
with librdkafka 0.11.6 and 1.0.0.

cons: Don't execute Poll & shutdown concurrently

---

Gopkg.lock
Gopkg.toml
README.md
consumer.go

This enables us to revert the workaround introduced in #61, which was
needed because of confluentinc/confluent-kafka-go#189.
That bug is fixed in librdkafka 0.11.5.
We also bump confluent-kafka-go to 1.0.0, which works with 0.11.5,
0.11.6 and 1.0.0.

Drop support for librdkafka 0.11.4 and before

---

consumer.go

When a Rafka consumer receives an `OffsetsCommitted` event it will log an array with information about the commited offsets. This array contains information about all partition/offset pairs in which the Rafka consumer has been subscribed to, regardless of the amount of data that have been actually commited by librdkafka.
For example, consider a topic with _12_ partitions; the `OffsetsCommitted` event of a single partition/offset pair (_part: 9_, _offset: 1_), looks like the following snippet:
```
[cgroup|cid|topic] 2019/08/02 13:43:36 OffsetsCommitted (<nil>, [topic[0]@unset topic[1]@unset topic[2]@unset topic[3]@unset topic[4]@unset topic[5]@unset topic[6]@unset topic[7]@unset topic[8]@unset topic[9]@1 topic[10]@unset topic[11]@unset])
```
This extraneous information makes debugging …

consumer: Drop invalid offsets from OffsetsCommitted output

---

README.md
client.go
server.go

[MONITOR](https://redis.io/commands/monitor) is a debugging command that streams back every command processed by the Redis server. Since Rafka does not log the commands that the server handles, adding the ability to _"attach a terminal on server"_ and listen to all requests received by the server in real-time, would be a quite useful addition in order to spot bugs easier in a Rafka application.
To enable this functionality, we add an extra channel to the `Client` struct, the `monitorChan`. A separate goroutine that is spawned at client's creation time, will stream any data written to that channel on the client's socket. On server-side, we maintain a syncmap of the clients' monitoring channels, named `monitorChans`. Each time a _MONITOR_ command is triggered, the respective client's …

Add support for the MONITOR command

---

CHANGELOG.md
client.go
config.go
consumer.go
consumer_manager.go
main.go
producer.go
stats.go

Release new Rafka v0.5.0:
- bump version string in main.go module
- update CHANGELOG accordingly and trim any redundant newline
- update date range on copyright notice

Release version 0.5.0

---

ddocs/design-rafka-rethinking.rst

This commit adds a design document detailing the plan for refactoring the internal structure of Rafka. Some sections included a `TODO` tag which means that it will be updated with more information in upcoming iterations.

ddocs: Add a design document for Rafka refactoring

---

CHANGELOG.md
main.go

This release refactors the internal data structures of Rafka. The external API and generally any
interaction with existing functionality is not affected. In short it implements the [Redefine Rafka
scope](https://github.com/skroutz/rafka/blob/master/docs/designs/design-rafka-rethinking.rst#redefine-rafka-scope) and [Drop redundant functionality](https://github.com/skroutz/rafka/blob/master/docs/designs/design-rafka-rethinking.rst#drop-redundant-functionality) proposals of the [Rafka Rethinking](https://github.com/skroutz/rafka/blob/master/docs/designs/design-rafka-rethinking.rst) design doc.
> **Note:** Initially we were targeting v1.0.0. However, since Rafka semantics remain intact there's no actual need to bump to `v1.0.0` for now; furthermore we should better "save" `v1.0.0` numbering …

Release v0.6.0

---

CHANGELOG.md
main.go

This is a maintenance release with a minor change; we've just added `debian/buster` to branches safelist.

Release version 0.6.1

---

.travis.yml
README.md
test/Dockerfile
test/Gemfile
test/Gemfile.lock
test/docker-compose.yml

This patchset enables us to set the Debian and librdkafka versions to use when running the tests. It then updates our Travis build to leverage this feature and test in both Debian Buster and Stretch with librdkafka 0.11.6 and 1.2.1.

test: Allow configuring Debian and librdkafka versions

---

debian/service

Since this is a critical piece of software, we should automatically
restart it if/when it fails.

systemd: restart rafka on failure

---

producer.go
stats.go

From [confluent-kafka-go documentation](https://github.com/confluentinc/confluent-kafka-go/blob/master/kafka/kafka.go#L74-L78):
```go
// * Producing is an asynchronous operation so the client notifies the application
// of per-message produce success or failure through something called delivery reports.
// Delivery reports are by default emitted on the `.Events()` channel as `*kafka.Message`
// and you should check `msg.TopicPartition.Error` for `nil` to find out if the message
// was succesfully delivered or not.
```
However, what they do not mention is that the `.Events()` channel does not always consist of `*kafka.Message`s. This is not so obvious, however they somewhat admit it in the [how to setup the producer example](https://github.com/confluentinc/confluent-kafka-go/blob/master/exa …

Producer ignorable events
